# Module: NumPy Assignments
## Lesson: NumPy


### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.


In [1]:
import numpy as np

In [7]:
m = np.random.randint(1, 20, (5,5))
m[:, 2] = 1

m

array([[ 9, 12,  1, 11, 15],
       [ 5,  5,  1,  9, 13],
       [11,  3,  1, 10,  5],
       [ 8, 18,  1,  9, 11],
       [14, 15,  1,  6, 10]])

In [32]:
r  = np.array(range(1, 17))
mask = [i == j for i in range(4) for j in range(4)]
r[mask] = 0
r.reshape(4, 4)

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.


In [35]:
r = np.arange(1, 37).reshape(6, 6)
r[2:6, 1:5]

array([[14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29],
       [32, 33, 34, 35]])

In [56]:
r = np.random.randint(1, 100, 25)
mask = np.array([i == 0 or j == 0 or i == 4 or j == 4 for i in range(5) for j in range(5)])

print(r.reshape(5, 5))
print(r[mask])

[[25 41 41  8 61]
 [61  4 49 65 20]
 [17 24  2 33 29]
 [58 72 21 25 68]
 [65 83 92 42 46]]
[25 41 41  8 61 61 20 17 29 58 68 65 83 92 42 46]



### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.



### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).


In [62]:
r = np.random.randint(1, 20, (5,5))
normalized_r = (r - r.mean()) / r.std()
normalized_r

array([[ 0.83305729,  1.20830833,  0.08255523, -1.41844891,  0.27018074],
       [ 0.27018074, -0.66794684,  1.20830833,  0.64543178,  1.77118488],
       [-1.60607442,  0.45780626, -0.48032132, -0.66794684, -1.41844891],
       [-0.66794684, -1.23082339,  0.45780626,  0.08255523,  1.58355936],
       [-0.66794684, -1.23082339,  1.39593384,  0.64543178, -0.85557236]])


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.


In [68]:
m = np.random.randint(1, 20, (3, 3))
n = np.array([1 , 1 , 1])

print(f"shape of m: {m.shape},  \nshape of n: {n.shape}")

print(f" original m: \n{m} \n")
print(f" original n: \n{n} \n")
print(f" m + n: \n{m + n} \n")

shape of m: (3, 3),  
shape of n: (3,)
 original m: 
[[ 9  6  4]
 [ 2  4  9]
 [12  2  5]] 

 original n: 
[1 1 1] 

 m + n: 
[[10  7  5]
 [ 3  5 10]
 [13  3  6]] 




### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.


In [71]:
m = np.random.random((3 ,3))
print(f"determinant of m : {np.linalg.det(m)} \ninverse of m : {np.linalg.inv(m)}\n eigen values of m : {np.linalg.eig(m)}")

determinant of m : 0.10364020295687176 
inverse of m : [[ 0.04502325  2.87888511 -1.68880708]
 [-0.07946367 -0.3548636   1.63173273]
 [ 2.28282554 -4.83818177  2.75838387]]
 eigen values of m : EigResult(eigenvalues=array([1.0011624 +0.j        , 0.07503662+0.31287278j,
       0.07503662-0.31287278j]), eigenvectors=array([[ 0.72762678+0.j        ,  0.41678846+0.21753397j,
         0.41678846-0.21753397j],
       [ 0.51011455+0.j        , -0.13224431-0.38618862j,
        -0.13224431+0.38618862j],
       [ 0.45863103+0.j        , -0.78251911+0.j        ,
        -0.78251911-0.j        ]]))


In [75]:
m1 = np.random.random((2 , 3))
m2 = np.random.random((3 , 2))

m1 @ m2

array([[0.35424694, 0.9072093 ],
       [0.30053893, 0.96317283]])


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).


In [78]:
n = np.random.randint(1, 10, (5, 5))
n.flatten()
n.reshape(1 , 25)

array([[3, 6, 2, 8, 1, 1, 5, 4, 2, 2, 5, 1, 7, 3, 6, 4, 4, 4, 2, 9, 4, 2,
        8, 8, 5]])


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.


In [82]:
m = np.random.randint(1, 20 , 25)
masking = [(i == 0 or i == 4) and (j == 0 or j == 4) for i in range(5) for j in range(5)]

print(f"original m: \n{m.reshape(5, 5)} \nekement on the border: \n{m[masking]}")


original m: 
[[ 8  9 14 18  9]
 [ 8 12  1  4 14]
 [ 7  7 16  3 18]
 [13 15  6  1  4]
 [12  5 13 12 13]] 
ekement on the border: 
[ 8  9 12 13]


In [84]:
m = np.random.randint(1, 20, 16)

print(f"original m: \n{m.reshape(4, 4)}")

m[m > 10] = 10

print(f"modified m: \n{m.reshape(4, 4)}")


original m: 
[[ 1  6  1 15]
 [10 15 17  9]
 [19 15  8 14]
 [11 14  7 13]]
modified m: 
[[ 1  6  1 10]
 [10 10 10  9]
 [10 10  8 10]
 [10 10  7 10]]



### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.


In [85]:
# 1. Structured array with fields 'name', 'age', 'weight', add data and sort by age
data = np.array([
    ('Alice', 25, 55.0),
    ('Bob', 30, 75.5),
    ('Charlie', 22, 68.0),
    ('David', 28, 80.2)
], dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

sorted_data = np.sort(data, order='age')
print("Sorted by age:\n", sorted_data)


Sorted by age:
 [('Charlie', 22, 68. ) ('Alice', 25, 55. ) ('David', 28, 80.2)
 ('Bob', 30, 75.5)]


In [86]:
# 2. Structured array with fields 'x', 'y', compute Euclidean distance between each pair
points = np.array([
    (1, 2),
    (4, 6),
    (7, 8)
], dtype=[('x', 'i4'), ('y', 'i4')])
points

array([(1, 2), (4, 6), (7, 8)], dtype=[('x', '<i4'), ('y', '<i4')])

In [90]:
coords = np.vstack((points['x'], points['y'])).T
coords

array([[1, 2],
       [4, 6],
       [7, 8]], dtype=int32)

In [96]:
diff = coords[:, np.newaxis, :] - coords[np.newaxis, :, :]
print(f"{coords[:, np.newaxis, :]}\n shpae: {coords[:, np.newaxis, :].shape}")
print(f"{coords[np.newaxis, :, :]}\n shpae: {coords[np.newaxis, :, :].shape}")
print(f"{diff}\n shpae: {diff.shape}")

[[[1 2]]

 [[4 6]]

 [[7 8]]]
 shpae: (3, 1, 2)
[[[1 2]
  [4 6]
  [7 8]]]
 shpae: (1, 3, 2)
[[[ 0  0]
  [-3 -4]
  [-6 -6]]

 [[ 3  4]
  [ 0  0]
  [-3 -2]]

 [[ 6  6]
  [ 3  2]
  [ 0  0]]]
 shpae: (3, 3, 2)


In [ ]:
distances = np.sqrt(np.sum(diff**2, axis=0))
#distances = np.sum(diff, axis=2)
print("Euclidean distances:\n", distances)


Euclidean distances:
 [[  0  -7 -12]
 [  7   0  -5]
 [ 12   5   0]]



### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.